In [1]:
# Import torch & Check CUDA availability
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())

True
1
0


In [2]:
# Get CUDA device name
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

NVIDIA A100 80GB PCIe


#### Import Graph500_Scale23_EdgeFactor64

In [3]:
# Import dataset from saved PyTorch dataset
data = torch.load("/dfs6/pub/seminl1/graph500/graph500_scale23_ef64.pt")

In [4]:
# Transform dense edge index to sparse adjacency matrix
import torch_geometric.transforms as T

data = T.ToSparseTensor()(data)
data = data.pin_memory()

#### Graph Information

In [6]:
# Print first element
print(f'Graph: {data}')

Graph: Data(x=[8388608, 64], y=[8388608], train_mask=[8388608], adj_t=[8388608, 8388608, nnz=517557419])


In [7]:
# Node feature matrix information
print(f'x = {data.x.shape}')
print(data.x)

x = torch.Size([8388608, 64])
tensor([[-1.6241, -1.1809,  1.4980,  ...,  1.0852, -1.1694,  0.5091],
        [-1.3206, -1.1632, -2.0369,  ..., -2.1283, -1.8054, -1.2949],
        [-1.2896,  1.1596,  1.6661,  ..., -0.4917,  1.7394,  2.0564],
        ...,
        [ 1.0796,  1.1860, -0.0762,  ..., -1.8736,  1.2661,  0.6824],
        [-1.4856,  2.1285, -1.8341,  ..., -1.8353,  0.8483, -0.7442],
        [-1.1195, -0.3819, -0.7515,  ..., -0.5175, -1.4563, -2.4408]])


In [8]:
# Adjacency matrix for the edges
print(data.adj_t)

SparseTensor(row=tensor([      0,       0,       0,  ..., 8388607, 8388607, 8388607]),
             col=tensor([      0,       1,       2,  ..., 1320822, 6800756, 8065975]),
             size=(8388608, 8388608), nnz=517557419, density=0.00%)


In [9]:
# Ground-truth labels
print(f'y = {data.y.shape}')
print(data.y)

y = torch.Size([8388608])
tensor([36, 21, 11,  ...,  6, 46, 53])


In [10]:
# Train mask
print(f'train_mask = {data.train_mask.shape}')
print(data.train_mask)

train_mask = torch.Size([8388608])
tensor([False,  True,  True,  ...,  True,  True, False])


#### Single-layer GCN

In [11]:
# Create a simple GCN with only one GCN layer
import torch.nn.functional as F

from torch.nn import Linear
from torch_geometric.nn import GCNConv

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.gcn1 = GCNConv(64, 64)
        self.optimizer = torch.optim.Adam(self.parameters(),
                                          lr=0.01,
                                          weight_decay=5e-4)

    def forward(self, x, adj_t):
        x = self.gcn1(x, adj_t)
        z = F.log_softmax(x, dim=1)
        return x, z

#### Do use mini-batch

In [12]:
def accuracy(pred_y, y):
    """Calculate accuracy."""
    return ((pred_y == y).sum() / len(y)).item()

def train(model, train_loader):
    """Train a GNN model and return the trained model."""
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = model.optimizer
    epochs = 100

    model.train()
    for epoch in range(epochs):
        #total_loss = 0
        #acc = 0
        #val_loss = 0
        #val_acc = 0
        
        # Train on batches
        for batch in train_loader:
            batch = batch.to('cuda:0', non_blocking=True)
            optimizer.zero_grad()
            h, out = model(batch.x, batch.adj_t)
            #loss = criterion(out[batch.train_mask], batch.y[batch.train_mask])
            #total_loss += loss
            #acc += accuracy(out[batch.train_mask].argmax(dim=1), batch.y[batch.train_mask])
            #loss.backward()
            optimizer.step()
        
        # Print metrics every 10 epochs
        if(epoch % 10 == 0):
            print('Epoch:', epoch)
            #print(f'Epoch {epoch:>3} | Train Loss: {total_loss/len(train_loader):.3f} | Train Acc: '
            #      f'{acc/len(train_loader)*100:>6.2f}%')

    return model, h, out

In [14]:
from torch_geometric.loader import NeighborLoader
    
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)

# Create GCN model
gcn = GCN()
print(gcn)
print()

# Create batches with neighbor sampling
start.record()
train_loader = NeighborLoader(
    data,
    num_neighbors=[-1],
    batch_size=131072,
    pin_memory=True,
    #num_workers=8,
    #prefetch_factor=1,
)

# Train
gcn_model, gcn_output, final_output = train(gcn.to('cuda:0'), train_loader)
end.record()
torch.cuda.synchronize()
elapsed_time = start.elapsed_time(end)
print('Elapsed Time (100 Epochs):', elapsed_time*0.001, 'seconds')

GCN(
  (gcn1): GCNConv(64, 64)
)

Epoch: 0
Epoch: 10
Epoch: 20
Epoch: 30
Epoch: 40
Epoch: 50
Epoch: 60
Epoch: 70
Epoch: 80
Epoch: 90
Epoch: 100


#### Do not use mini-batch

In [13]:
def accuracy(pred_y, y):
    """Calculate accuracy."""
    return ((pred_y == y).sum() / len(y)).item()

def train(model, data):
    """Train a GNN model and return the trained model."""
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = model.optimizer
    epochs = 100

    model.train()
    for epoch in range(epochs):
        # Training
        optimizer.zero_grad()
        h, out = model(data.x, data.adj_t)
        #loss = criterion(out[data.train_mask], data.y[data.train_mask])
        #acc = accuracy(out[data.train_mask].argmax(dim=1), data.y[data.train_mask])
        #loss.backward()
        optimizer.step()

        # Print metrics every 10 epochs
        if(epoch % 10 == 0):
            print('Epoch:', epoch)
            #print(f'Epoch {epoch:>3} | Train Loss: {loss:.3f} | Train Acc: {acc*100:>6.2f}%')
          
    return model, h, out

In [14]:
start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)

# Create GCN model
gcn = GCN()
print(gcn)
print()

# Train
start.record()
gcn_model, gcn_output, final_output = train(gcn.to('cuda:0'), data.to('cuda:0', non_blocking=True))
end.record()
torch.cuda.synchronize()
elapsed_time = start.elapsed_time(end)
print('Elapsed Time (100 Epochs):', elapsed_time*0.001, 'seconds')

GCN(
  (gcn1): GCNConv(64, 64)
)

Epoch   0 | Train Loss: 4.493 | Train Acc:   1.56%
Epoch  10 | Train Loss: 4.217 | Train Acc:   1.57%
Epoch  20 | Train Loss: 4.165 | Train Acc:   1.58%
Epoch  30 | Train Loss: 4.165 | Train Acc:   1.59%
Epoch  40 | Train Loss: 4.161 | Train Acc:   1.61%
Epoch  50 | Train Loss: 4.159 | Train Acc:   1.63%
Epoch  60 | Train Loss: 4.158 | Train Acc:   1.64%
Epoch  70 | Train Loss: 4.158 | Train Acc:   1.65%
Epoch  80 | Train Loss: 4.158 | Train Acc:   1.66%
Epoch  90 | Train Loss: 4.158 | Train Acc:   1.66%
Epoch 100 | Train Loss: 4.158 | Train Acc:   1.67%
